name: Upload Release

run-name: Building and uploading release

on:
  push:
    branches: [ feature/actions-test ]

jobs:
  set-up:
    runs-on: ubuntu-latest
 
    permissions:
      contents: write
 
    steps:
      - name: Setup Py
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install spatialize
        run: pip install spatialize

      - name: Install wheel
        run: pip install build

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    needs:
      - set-up
    
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Build
        run: python -m build

  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs:
      - build

    steps:
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
        
