name: Test

run-name: Running test on Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
 
    permissions:
      contents: write
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Setup Py
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: debug ls
        run: ls -R
 
      - name: Run example script
        run: python examples/scripted_examples/esi_3d_nongriddata.py
         
